name: melonds-emulator
base: core24
version: '1.0'
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
summary: Nintendo DS and DSi emulator
description: |
   melonDS aims at providing fast and accurate Nintendo DS emulation. While it is still a work in progress, it has a pretty solid set of features.

    Nearly complete core (CPU, video, audio, ...)
    OpenGL renderer, 3D upscaling
    RTC, microphone, lid close/open
    Joystick support
    Savestates
    Various display position/sizing/rotations modes
    Work-in-progress Wi-Fi emulation for online connectivity and local multiplayer
    Experimental emulation of the Nintendo DSi
    ...and even more is planned!
grade: stable
confinement: strict

apps:
  melonds-emulator:
    command: usr/games/melonDS
    desktop: usr/gui/MelonDS-emulator.desktop
    common-id: net.kuribo64.melonDS
    extensions: [kde-neon-6]
    plugs:
      - unity7
      - screen-inhibit-control
      - audio-playback
      - network
      - network-bind
      - home
      - removable-media
      - mount-observe
      - joystick
      - bluez

plugs:
  shared-memory:
    private: true
  kvantum:
    content: kvantum
    interface: content
    target: $SNAP/kvantum
    default-provider: qt-style-kvantum

environment:
  QT_PLUGIN_PATH: $SNAP/kvantum/usr/lib/x86_64-linux-gnu/qt6/plugins${QT_PLUGIN_PATH:+:$QT_PLUGIN_PATH}

layout:
  /usr/share/color-schemes:
    symlink: $SNAP/kvantum/usr/share/color-schemes
  /usr/share/Kvantum:
    symlink: $SNAP/kvantum/usr/share/Kvantum

parts:
  melonds:
    plugin: dump
    source:
      - on amd64: https://github.com/melonDS-emu/melonDS/releases/download/1.0/melonDS-ubuntu-x86_64.zip
      - on arm64: https://github.com/melonDS-emu/melonDS/releases/download/1.0/melonDS-ubuntu-aarch64.zip
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/games/
      mv -f melonDS $CRAFT_PART_INSTALL/usr/games/
      chmod 777 $CRAFT_PART_INSTALL/usr/games/melonDS
    prime:
      - usr/games/melonDS

  launcher:
    after: [melonds]
    plugin: nil
    source: ./launcher
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/gui
      mv -f MelonDS-emulator.desktop $CRAFT_PART_INSTALL/usr/gui/
      mv -f MelonDS-emulator.svg $CRAFT_PART_INSTALL/usr/gui/
    prime:
      - usr/gui/
      
  dependencies:
    after: [launcher]
    plugin: nil
    stage-packages:
      - libsdl2-2.0-0
      - libenet7
      - libdecor-0-0
    prime:
      - usr/lib/x86_64-linux-gnu/libSDL2-2.0.so*
      - usr/lib/x86_64-linux-gnu/libenet.so*
      - usr/lib/x86_64-linux-gnu/libdecor-0.so*
