name: melonds-emulator
base: core24
version: '1.1'
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
summary: Nintendo DS and DSi emulator
description: |
   melonDS aims at providing fast and accurate Nintendo DS emulation. While it is still a work in progress, it has a pretty solid set of features.

    Nearly complete core (CPU, video, audio, ...)
    OpenGL renderer, 3D upscaling
    RTC, microphone, lid close/open
    Joystick support
    Savestates
    Various display position/sizing/rotations modes
    Work-in-progress Wi-Fi emulation for online connectivity and local multiplayer
    Experimental emulation of the Nintendo DSi
    ...and even more is planned!
grade: stable
confinement: strict
icon: melon.svg

apps:
  melonds-emulator:
    command: melonDS
    desktop: net.kuribo64.melonDS.desktop
    common-id: net.kuribo64.melonDS
    environment:
      QT_QPA_PLATFORMTHEME: xdgdesktopportal
      LD_LIBRARY_PATH: $SNAP/lxqt-support-core24/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
      QT_PLUGIN_PATH: $SNAP/lxqt-support-core24/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins:$QT_PLUGIN_PATH
    extensions: [kde-neon-6]
    plugs:
      - unity7
      - screen-inhibit-control
      - audio-playback
      - network
      - network-bind
      - home
      - removable-media
      - mount-observe
      - joystick
      - bluez

plugs:
  shared-memory:
    private: true
  lxqt-support-core24:
    content: lxqt-support-core24
    interface: content
    target: $SNAP/lxqt-support-core24
    default-provider: lxqt-support-core24

layout:
  /usr/share/color-schemes:
    symlink: $SNAP/lxqt-support-core24/usr/share/color-schemes
  /usr/share/Kvantum:
    symlink: $SNAP/lxqt-support-core24/usr/share/Kvantum

parts:
  melonds-app:
    plugin: dump
    source:
      - on amd64: https://github.com/melonDS-emu/melonDS/releases/download/$SNAPCRAFT_PROJECT_VERSION/melonDS-$SNAPCRAFT_PROJECT_VERSION-ubuntu-x86_64.zip
      - on arm64: https://github.com/melonDS-emu/melonDS/releases/download/$SNAPCRAFT_PROJECT_VERSION/melonDS-$SNAPCRAFT_PROJECT_VERSION-ubuntu-aarch64.zip
    prime:
      - melonDS
      
  dependencies:
    after: [melonds-app]
    plugin: nil
    stage-packages:
      - libsdl2-2.0-0
      - libenet7
      - libdecor-0-0
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libSDL2-2.0.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libenet.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdecor-0.so*

  dot-desktop:
    after: [dependencies]
    plugin: dump
    source: ./dot-desktop
    prime:
      - net.kuribo64.melonDS.desktop